sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 893640
  alioss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    access-key-id: LTAI5tAvGeKFv9WrfTEV9Y26
    access-key-secret: Xd59ljKqLunuyviI10HqwL0hvsA911
    bucket-name: vizzini-sky-takeout